//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSLibreCell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSLibreCell.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose game by ID.
        /// </summary>
        internal static string ChooseDialog_Title {
            get {
                return ResourceManager.GetString("ChooseDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is known to be unwinnable.
        /// </summary>
        internal static string GameIsUnwinnable {
            get {
                return ResourceManager.GetString("GameIsUnwinnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS.
        /// </summary>
        internal static string GameWonMessage {
            get {
                return ResourceManager.GetString("GameWonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSLibreCell - A FreeCell implementation.
        ///
        ///This help: {18}
        ///Status: {19}
        ///New random game: {20}
        ///Choose Game: {21}
        ///
        ///Making moves: specify source and destination using:
        ///{0} {1} {2} {3} || {4} {5} {6} {7}
        /// {8} {9} {10} {11} {12} {13} {14} {15}
        ///
        ///Cancel move: {16}
        ///Unlimited undo: {17}.
        /// </summary>
        internal static string HelpDialog_ContentTemplate {
            get {
                return ResourceManager.GetString("HelpDialog_ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpDialog_Title {
            get {
                return ResourceManager.GetString("HelpDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Choose.
        /// </summary>
        internal static string MenuBar_Choose {
            get {
                return ResourceManager.GetString("MenuBar_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new game to start.
        /// </summary>
        internal static string MenuBar_ChooseHint {
            get {
                return ResourceManager.GetString("MenuBar_ChooseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Game.
        /// </summary>
        internal static string MenuBar_Game {
            get {
                return ResourceManager.GetString("MenuBar_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string MenuBar_Help {
            get {
                return ResourceManager.GetString("MenuBar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _?.
        /// </summary>
        internal static string MenuBar_Other {
            get {
                return ResourceManager.GetString("MenuBar_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        internal static string MenuBar_Quit {
            get {
                return ResourceManager.GetString("MenuBar_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Random.
        /// </summary>
        internal static string MenuBar_Random {
            get {
                return ResourceManager.GetString("MenuBar_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new random game.
        /// </summary>
        internal static string MenuBar_RandomHint {
            get {
                return ResourceManager.GetString("MenuBar_RandomHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Status.
        /// </summary>
        internal static string MenuBar_Status {
            get {
                return ResourceManager.GetString("MenuBar_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo last move.
        /// </summary>
        internal static string MenuBar_Undo {
            get {
                return ResourceManager.GetString("MenuBar_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}.
        /// </summary>
        internal static string StatusDialog_ContentTemplate {
            get {
                return ResourceManager.GetString("StatusDialog_ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey 1-64000 completed!.
        /// </summary>
        internal static string StatusDialog_Finished {
            get {
                return ResourceManager.GetString("StatusDialog_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First stage of journey: 1-32000.
        /// </summary>
        internal static string StatusDialog_FirstStage {
            get {
                return ResourceManager.GetString("StatusDialog_FirstStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey not started..
        /// </summary>
        internal static string StatusDialog_NotStarted {
            get {
                return ResourceManager.GetString("StatusDialog_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of 32000 games in stage completed.
        /// </summary>
        internal static string StatusDialog_ProgressTemplate {
            get {
                return ResourceManager.GetString("StatusDialog_ProgressTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second stage of journey: 32001-64000.
        /// </summary>
        internal static string StatusDialog_SecondStage {
            get {
                return ResourceManager.GetString("StatusDialog_SecondStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusDialog_Title {
            get {
                return ResourceManager.GetString("StatusDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSLibreCell.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
